### ISSUE TITLE
v1.2.6: Deno throws because of Node related code 

### ISSUE THREAD

**Issue by lilnasy** [paulmillr/noble-ed25519#28]
Last working version: 1.0.1
```
Deno 1.14.2
exit using ctrl+d or close()
> import * as ed from 'https://deno.land/x/ed25519/mod.ts';
Check https://deno.land/x/ed25519/mod.ts
Uncaught TypeError: TS2580 [ERROR]: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
    typeof module !== 'undefined' &&
           ~~~~~~
    at https://deno.land/x/ed25519@1.2.6/index.ts:762:12

TS2580 [ERROR]: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
    typeof module.require === 'function' &&
           ~~~~~~
    at https://deno.land/x/ed25519@1.2.6/index.ts:763:12

TS2580 [ERROR]: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
    module.require.bind(module);
    ~~~~~~
    at https://deno.land/x/ed25519@1.2.6/index.ts:764:5

TS2580 [ERROR]: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
    module.require.bind(module);
                        ~~~~~~
    at https://deno.land/x/ed25519@1.2.6/index.ts:764:25

Found 4 errors.
    at async <anonymous>:2:12
```

**Comment by paulmillr** [comment]
Fixed in 1.3.2 @lilnasy @dimroc @cky

**Comment by paulmillr** [comment]
Make sure to check out the README for updated usage with deno.

**Comment by lilnasy** [comment]
genius
