### ISSUE TITLE
window.crypto is not available over LAN HTTP

### ISSUE THREAD

**Issue by joepio** [paulmillr/noble-ed25519#38]
Hi there! Thanks for creating this :)

After updating from `noble-ed25519 1.0.4` to `@noble/ed25519 1.33`, I got this error in an `http` context: `Na.web.subtle is undefined`. I'm not _entirely_ sure whether this error would have appeared before. 

It seems to appear only if I'm running my server on a local network system using HTTP, but not on localhost or in HTTPS in production.

The code seems to emerges from [here](https://github.com/paulmillr/noble-ed25519/blob/321ba831185bd22764d4a3621c1bfcfe75b9561f/index.ts#L831).

After some googling I learned that the `crypto` module is not available in non-localhost HTTP environments. 

So what does this mean for me as a user of this dependency? I feel like, in my usecase, it should be able to run in HTTP contexts, so I'd like some fallback. Should this library provide a fallback? Should I as a user of this library provide a fallback, or show some custom error? Would love to hear your thoughts on this.

Thanks!

**Comment by paulmillr** [comment]
Hey there.

You could replace hashing code with code from `noble-crypto`. It's an interesting problem, because even though hashes could be replaced, `randomBytes` cannot. `randomBytes` also cannot be re-implemented in JS, it needs low-level system entropy. ed25519 does not really use randomness in its flow, but secp256k1 schnorr sigs do.

We won't include fallback by default because we don't want any deps.

**Comment by paulmillr** [comment]
For now, you can edit your fork of noble-ed to replace sha512 with `noble-hashes/sha512`

**Comment by paulmillr** [comment]
Ah, crypto.getRandom does not require a secure context, so that's a good start.

**Comment by paulmillr** [comment]
Try this:

```
const { sha512 } = require('@noble/hashes/sha512');
ed25519.utils.sha512 = (msg) => Promise.resolve(sha512(msg))
```

**Comment by joepio** [comment]
Will do!

**Comment by joepio** [comment]
Seems like I can't build `@noble/hashes` for some reason:

```
erna ERR! yarn run build stderr:
 > publish/dist/pkg/json-stable-stringify.js:335:13: warning: The "typeof" operator will never evaluate to "null"
    335 │         case 'null':
        ╵              ~~~~~~

[
  {
    detail: undefined,
    location: {
      column: 13,
      file: 'publish/dist/pkg/json-stable-stringify.js',
      length: 6,
      line: 335,
      lineText: "        case 'null':",
      namespace: ''
    },
    notes: [],
    text: 'The "typeof" operator will never evaluate to "null"'
  }
]
[20:12:16] [snowpack] rimrafSafe(): /Users/joep/dev/github/joepio/atomic-data-browser/node_modules/@noble/hashes/cryptoBrowser.js outside of buildOptions.out /Users/joep/dev/github/joepio/atomic-data-browser/data-browser/publish
[20:12:16] [snowpack] Error: rimrafSafe(): /Users/joep/dev/github/joepio/atomic-data-browser/node_modules/@noble/hashes/cryptoBrowser.js outside of buildOptions.out /Users/joep/dev/github/joepio/atomic-data-browser/data-browser/publish
    at Object.deleteFromBuildSafe (/Users/joep/dev/github/joepio/atomic-data-browser/node_modules/snowpack/lib/cjs/util.js:75:15)
    at Object.runBuiltInOptimize (/Users/joep/dev/github/joepio/atomic-data-browser/node_modules/snowpack/lib/cjs/build/optimize.js:419:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.optimize (/Users/joep/dev/github/joepio/atomic-data-browser/node_modules/snowpack/lib/cjs/build/process.js:299:9)
    at async build (/Users/joep/dev/github/joepio/atomic-data-browser/node_modules/snowpack/lib/cjs/commands/build.js:18:5)
    at async Object.command (/Users/joep/dev/github/joepio/atomic-data-browser/node_modules/snowpack/lib/cjs/commands/build.js:35:9)
    at async cli (/Users/joep/dev/github/joepio/atomic-data-browser/node_modules/snowpack/lib/cjs/index.js:174:9)
```

**Comment by paulmillr** [comment]
Report this to snowpack.

**Comment by joepio** [comment]
Seems to be [this](https://github.com/withastro/snowpack/issues/3403). Sorry, this blocks me from testing your fix at the moment.

**Comment by joepio** [comment]
I've found a workaround to build it, and I can confirm your fix works, @paulmillr !

Thanks for the help :)
