### ISSUE TITLE
The package ( @noble/ed25519 ) is throwing some math errors in production works fine in local

### ISSUE THREAD

**Issue by rajathongal** [paulmillr/noble-ed25519#68]
Usage of the module 

```
import * as ed from '@noble/ed25519';

const someFunction = async() => {
    const privateKeyRaw = ed.utils.randomPrivateKey(); // 32-byte Uint8Array or string.
    const publicKeyRaw = await ed.getPublicKey(privateKeyRaw);
}
```

I'm using this in a react app onClick the function triggers but on production even before the button is pressed I'm getting this error

```
TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at 88238 (index.js:7:21)
    at __webpack_require__ (create fake namespace object:19:32)
    at 26554 (392.8554e2b8.chunk.js:1:221)
    at Function.__webpack_require__ (create fake namespace object:19:32)

```
![image](https://user-images.githubusercontent.com/51845795/189539502-d668f849-a025-464f-ac7c-e1941f946d69.png)

I believe the error is arising from the import statement.

**Comment by RunHippo** [comment]
I also have this problem

**Comment by paulmillr** [comment]
update to `1.7.0`

**Comment by paulmillr** [comment]
update to `1.7.1`
