### ISSUE TITLE
deno support

### ISSUE THREAD

**Issue by pgg** [paulmillr/noble-ed25519#7]
is this suppose to work with deno? https://deno.land/x/ed25519/ advertises so, but when I run it i get:

```error TS2531: Object is possibly 'null'.

► https://raw.githubusercontent.com/paulmillr/noble-ed25519/0.7.0/index.ts:513:26

513     const buffer = await window.crypto.subtle.digest('SHA-512', message.buffer);
                             ~~~~~~~~~~~~~~~~~~~~

error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.

► https://raw.githubusercontent.com/paulmillr/noble-ed25519/0.7.0/index.ts:519:19

519 } else if (typeof process === 'object' && 'node' in process.versions) {
                      ~~~~~~~

error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.

► https://raw.githubusercontent.com/paulmillr/noble-ed25519/0.7.0/index.ts:519:53

519 } else if (typeof process === 'object' && 'node' in process.versions) {
                                                        ~~~~~~~

error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.

► https://raw.githubusercontent.com/paulmillr/noble-ed25519/0.7.0/index.ts:520:15

520   const req = require;```

**Comment by paulmillr** [comment]
it should work, but it seems like we need to fix it

**Comment by pgg** [comment]
```import * as ed from 'https://raw.githubusercontent.com/paulmillr/noble-ed25519/0.7.0/index.ts';

const PRIVATE_KEY = ed.utils.randomPrivateKey();
const HASH_MESSAGE = 'deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef';

const publicKey = await ed.getPublicKey(PRIVATE_KEY);
const signature = await ed.sign(HASH_MESSAGE, PRIVATE_KEY);
const isMessageSigned = await ed.verify(signature, HASH_MESSAGE, publicKey);

console.info(publicKey, signature, isMessageSigned);```

**Comment by christianbundy** [comment]
I got Deno working with this library, but I couldn't figure out how to run the tests easily since they depend on Node.js for opening files and such. Maybe someone else can take it to the finish line?

https://github.com/christianbundy/noble-ed25519/tree/deno

(No guarantees that I haven't broken anything, use at your own risk.)

**Comment by christianbundy** [comment]
Thanks for the fix! I'm still seeing the old problems, could you help me figure out what I'm doing wrong?

```console
$ deno --version
deno 1.0.0
v8 8.4.300
typescript 3.9.2
$ deno run https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/mod.ts
Compile https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/mod.ts
error: TS2531 [ERROR]: Object is possibly 'null'.
    const buffer = await window.crypto.subtle.digest('SHA-512', message.buffer);
                         ~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/index.ts:514:26

TS2580 [ERROR]: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.
} else if (typeof process === 'object' && 'node' in process.versions) {
                  ~~~~~~~
    at https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/index.ts:520:19

TS2580 [ERROR]: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.
} else if (typeof process === 'object' && 'node' in process.versions) {
                                                    ~~~~~~~
    at https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/index.ts:520:53

TS2580 [ERROR]: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.
  const { createHash, randomBytes } = require('crypto');
                                      ~~~~~~~
    at https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/index.ts:521:39

Found 4 errors.

**Comment by paulmillr** [comment]
```
test ❯ cat a.ts 
import * as ed from 'https://deno.land/x/ed25519/mod.ts';
const PRIVATE_KEY = ed.utils.randomPrivateKey(); // 32-byte Uint8Array or string.
const HASH_MESSAGE = 'deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef';
const publicKey = await ed.getPublicKey(PRIVATE_KEY);
console.log(publicKey)
test ❯ deno run a.ts 
Uint8Array(32) [
  228,  5, 212, 192, 244,  83, 151, 120,
  238, 29,  77, 106, 177, 250, 129, 255,
  105, 61, 194,  34,  81, 101,  98,  11,
  180, 33, 220, 255, 179, 158,  17, 130
]
```

**Comment by christianbundy** [comment]
Maybe a silly question (sorry), but what's the difference between running from github.com vs deno.land?

```console
$ deno run https://deno.land/x/ed25519/mod.ts
$ echo "no errors above"
no errors above
$ deno run https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/mod.ts
Compile https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/mod.ts
error: TS2531 [ERROR]: Object is possibly 'null'.
    const buffer = await window.crypto.subtle.digest('SHA-512', message.buffer);
                         ~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/index.ts:514:26

TS2580 [ERROR]: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.
} else if (typeof process === 'object' && 'node' in process.versions) {
                  ~~~~~~~
    at https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/index.ts:520:19

TS2580 [ERROR]: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.
} else if (typeof process === 'object' && 'node' in process.versions) {
                                                    ~~~~~~~
    at https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/index.ts:520:53

TS2580 [ERROR]: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.
  const { createHash, randomBytes } = require('crypto');
                                      ~~~~~~~
    at https://raw.githubusercontent.com/paulmillr/noble-ed25519/master/index.ts:521:39

Found 4 errors.

**Comment by paulmillr** [comment]
yeah, you should use official modules @ deno.land

**Comment by paulmillr** [comment]
curl gives us:

`content-type: application/typescript; charset=utf-8` for deno
`Content-Type: text/plain; charset=utf-8` for gh

**Comment by christianbundy** [comment]
Looks like `rm -rf ~/.cache/deno` did the trick. I don't know what deno.land is doing to circumvent it, but I'll use permalinks when pulling from GH in the future. Thanks for your help!
